### ISSUE TITLE
How to escape keywords

### ISSUE THREAD

**Issue by Bobi-zhou** [zeroSteiner/rule-engine#79]
example
```python
import rule_engine
# match a literal first name and applying a regex to the email
rule = rule_engine.Rule(
    'in.a==1 and first_name == "Luke" and email =~ ".*@rebels.org$"'
) # => <Rule text='first_name == "Luke" and email =~ ".*@rebels.org$"' >
print(rule.matches({
    'first_name': 'Luke', 'last_name': 'Skywalker', 'email': 'luke@rebels.org','in':{'a':1}
})) # => True
```
raise error
```python
Traceback (most recent call last):
  File "D:\Program Files\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\61912\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.
py", line 39, in <module>
    cli.main()
  File "c:\Users\61912\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugp
y\server\cli.py", line 430, in main
    run()
  File "c:\Users\61912\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugp
y\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\61912\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line
 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\61912\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line
 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\61912\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line
 124, in _run_code
    exec(code, run_globals)
  File "D:\Users\61912\PycharmProjects\device-emulator\1.py", line 18, in <module>
    rule = rule_engine.Rule(
           ^^^^^^^^^^^^^^^^^
  File "d:\Users\61912\PycharmProjects\device-emulator\.venv\Lib\site-packages\rule_engine\engine.py", line 499, in __init__
    self.statement = self.parser.parse(text, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\61912\PycharmProjects\device-emulator\.venv\Lib\site-packages\rule_engine\parser.py", line 102, in parse
    result = self._parser.parse(text, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\61912\PycharmProjects\device-emulator\.venv\Lib\site-packages\ply\yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\61912\PycharmProjects\device-emulator\.venv\Lib\site-packages\ply\yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\61912\PycharmProjects\device-emulator\.venv\Lib\site-packages\ply\yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
        ^^^^^^^^^^^^^^^^
  File "d:\Users\61912\PycharmProjects\device-emulator\.venv\Lib\site-packages\rule_engine\parser.py", line 297, in p_error
    raise errors.RuleSyntaxError('syntax error', token)
rule_engine.errors.RuleSyntaxError: ('syntax error', LexToken(IN,'in',1,0))
```

How can I escape keywords?

**Comment by zeroSteiner** [comment]
You don't. You'd need to access them as strings in a dictionary to provide encapsulation. Keywords are effectively reserved.

**Comment by Bobi-zhou** [comment]
> You don't. You'd need to access them as strings in a dictionary to provide encapsulation. Keywords are effectively reserved.


How should I write the code for the data provided in the example?

**Comment by zeroSteiner** [comment]
You'd make the rule something like `thing['in'].a == 1`.
