### ISSUE TITLE
rule_engine.errors.SymbolResolutionError, Symbol not found although it is in the dict and works in the debug_repl.

### ISSUE THREAD

**Issue by rsacherer** [zeroSteiner/rule-engine#99]
Hi, 

I am trying to implement your library in a project of mine, but for some reason I get error messages which I just can't understand. 

I have the following rule:
```
[ osd_metadata[osd].mem_swap_kb.to_int > 0 for osd in osd_metadata.keys ]
```

with the following dict:
```
{'osd_metadata': {'0': {'hostname': 'fedora', 'arch': 'x86_64', 'back_addr': '[v2:127.0.0.1:6804/1304773308,v1:127.0.0.1:6805/1304773308]', 'back_iface': '', 'bluefs': '1', 'bluefs_db_access_mode': 'file', 'bluefs_db_block_size': '4096', 'bluefs_db_driver': 'KernelDevice', 'bluefs_db_optimal_io_size': '0', 'bluefs_db_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd0/block.db', 'bluefs_db_rotational': '1', 'bluefs_db_size': '1073741824', 'bluefs_db_support_discard': '0', 'bluefs_db_type': 'hdd', 'bluefs_dedicated_db': '1', 'bluefs_dedicated_wal': '1', 'bluefs_single_shared_device': '0', 'bluefs_wal_access_mode': 'file', 'bluefs_wal_block_size': '4096', 'bluefs_wal_driver': 'KernelDevice', 'bluefs_wal_optimal_io_size': '0', 'bluefs_wal_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd0/block.wal', 'bluefs_wal_rotational': '1', 'bluefs_wal_size': '1048576000', 'bluefs_wal_support_discard': '0', 'bluefs_wal_type': 'hdd', 'bluestore_allocation_from_file': '0', 'bluestore_bdev_access_mode': 'file', 'bluestore_bdev_block_size': '4096', 'bluestore_bdev_driver': 'KernelDevice', 'bluestore_bdev_optimal_io_size': '0', 'bluestore_bdev_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd0/block', 'bluestore_bdev_rotational': '1', 'bluestore_bdev_size': '107374182400', 'bluestore_bdev_support_discard': '0', 'bluestore_bdev_type': 'hdd', 'bluestore_min_alloc_size': '4096', 'ceph_release': 'squid', 'ceph_version': 'ceph version 5f64facd06 (05f64facd06927d52075c67e8f3fb02753c5825c) squid (dev)', 'ceph_version_short': '5f64facd06', 'ceph_version_when_created': 'ceph version 5f64facd06 (05f64facd06927d52075c67e8f3fb02753c5825c) squid (dev)', 'cpu': '11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz', 'created_at': '2024-12-01T08:08:14.943408Z', 'default_device_class': 'hdd', 'device_ids': '', 'device_paths': '', 'devices': '', 'distro': 'fedora', 'distro_description': 'Fedora Linux 40 (Workstation Edition)', 'distro_version': '40', 'front_addr': '[v2:127.0.0.1:6802/1304773308,v1:127.0.0.1:6803/1304773308]', 'front_iface': '', 'hb_back_addr': '[v2:127.0.0.1:6808/1304773308,v1:127.0.0.1:6809/1304773308]', 'hb_front_addr': '[v2:127.0.0.1:6806/1304773308,v1:127.0.0.1:6807/1304773308]', 'journal_rotational': '1', 'kernel_description': '#1 SMP PREEMPT_DYNAMIC Fri Nov  1 16:09:34 UTC 2024', 'kernel_version': '6.11.6-200.fc40.x86_64', 'mem_swap_kb': '8388604', 'mem_total_kb': '65538576', 'network_numa_unknown_ifaces': 'back_iface,front_iface', 'os': 'Linux', 'osd_data': '/home/rsachere/Src/redhat/ceph/build/dev/osd0', 'osd_objectstore': 'bluestore', 'osdspec_affinity': '', 'rotational': '1'}, '1': {'hostname': 'fedora', 'arch': 'x86_64', 'back_addr': '[v2:127.0.0.1:6812/1975075424,v1:127.0.0.1:6813/1975075424]', 'back_iface': '', 'bluefs': '1', 'bluefs_db_access_mode': 'file', 'bluefs_db_block_size': '4096', 'bluefs_db_driver': 'KernelDevice', 'bluefs_db_optimal_io_size': '0', 'bluefs_db_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd1/block.db', 'bluefs_db_rotational': '1', 'bluefs_db_size': '1073741824', 'bluefs_db_support_discard': '0', 'bluefs_db_type': 'hdd', 'bluefs_dedicated_db': '1', 'bluefs_dedicated_wal': '1', 'bluefs_single_shared_device': '0', 'bluefs_wal_access_mode': 'file', 'bluefs_wal_block_size': '4096', 'bluefs_wal_driver': 'KernelDevice', 'bluefs_wal_optimal_io_size': '0', 'bluefs_wal_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd1/block.wal', 'bluefs_wal_rotational': '1', 'bluefs_wal_size': '1048576000', 'bluefs_wal_support_discard': '0', 'bluefs_wal_type': 'hdd', 'bluestore_allocation_from_file': '0', 'bluestore_bdev_access_mode': 'file', 'bluestore_bdev_block_size': '4096', 'bluestore_bdev_driver': 'KernelDevice', 'bluestore_bdev_optimal_io_size': '0', 'bluestore_bdev_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd1/block', 'bluestore_bdev_rotational': '1', 'bluestore_bdev_size': '107374182400', 'bluestore_bdev_support_discard': '0', 'bluestore_bdev_type': 'hdd', 'bluestore_min_alloc_size': '4096', 'ceph_release': 'squid', 'ceph_version': 'ceph version 5f64facd06 (05f64facd06927d52075c67e8f3fb02753c5825c) squid (dev)', 'ceph_version_short': '5f64facd06', 'ceph_version_when_created': 'ceph version 5f64facd06 (05f64facd06927d52075c67e8f3fb02753c5825c) squid (dev)', 'cpu': '11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz', 'created_at': '2024-12-01T08:08:22.134105Z', 'default_device_class': 'hdd', 'device_ids': '', 'device_paths': '', 'devices': '', 'distro': 'fedora', 'distro_description': 'Fedora Linux 40 (Workstation Edition)', 'distro_version': '40', 'front_addr': '[v2:127.0.0.1:6810/1975075424,v1:127.0.0.1:6811/1975075424]', 'front_iface': '', 'hb_back_addr': '[v2:127.0.0.1:6816/1975075424,v1:127.0.0.1:6817/1975075424]', 'hb_front_addr': '[v2:127.0.0.1:6814/1975075424,v1:127.0.0.1:6815/1975075424]', 'journal_rotational': '1', 'kernel_description': '#1 SMP PREEMPT_DYNAMIC Fri Nov  1 16:09:34 UTC 2024', 'kernel_version': '6.11.6-200.fc40.x86_64', 'mem_swap_kb': '8388604', 'mem_total_kb': '65538576', 'network_numa_unknown_ifaces': 'back_iface,front_iface', 'os': 'Linux', 'osd_data': '/home/rsachere/Src/redhat/ceph/build/dev/osd1', 'osd_objectstore': 'bluestore', 'osdspec_affinity': '', 'rotational': '1'}, '2': {'hostname': 'fedora', 'arch': 'x86_64', 'back_addr': '[v2:127.0.0.1:6820/298274492,v1:127.0.0.1:6821/298274492]', 'back_iface': '', 'bluefs': '1', 'bluefs_db_access_mode': 'file', 'bluefs_db_block_size': '4096', 'bluefs_db_driver': 'KernelDevice', 'bluefs_db_optimal_io_size': '0', 'bluefs_db_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd2/block.db', 'bluefs_db_rotational': '1', 'bluefs_db_size': '1073741824', 'bluefs_db_support_discard': '0', 'bluefs_db_type': 'hdd', 'bluefs_dedicated_db': '1', 'bluefs_dedicated_wal': '1', 'bluefs_single_shared_device': '0', 'bluefs_wal_access_mode': 'file', 'bluefs_wal_block_size': '4096', 'bluefs_wal_driver': 'KernelDevice', 'bluefs_wal_optimal_io_size': '0', 'bluefs_wal_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd2/block.wal', 'bluefs_wal_rotational': '1', 'bluefs_wal_size': '1048576000', 'bluefs_wal_support_discard': '0', 'bluefs_wal_type': 'hdd', 'bluestore_allocation_from_file': '0', 'bluestore_bdev_access_mode': 'file', 'bluestore_bdev_block_size': '4096', 'bluestore_bdev_driver': 'KernelDevice', 'bluestore_bdev_optimal_io_size': '0', 'bluestore_bdev_path': '/home/rsachere/Src/redhat/ceph/build/dev/osd2/block', 'bluestore_bdev_rotational': '1', 'bluestore_bdev_size': '107374182400', 'bluestore_bdev_support_discard': '0', 'bluestore_bdev_type': 'hdd', 'bluestore_min_alloc_size': '4096', 'ceph_release': 'squid', 'ceph_version': 'ceph version 5f64facd06 (05f64facd06927d52075c67e8f3fb02753c5825c) squid (dev)', 'ceph_version_short': '5f64facd06', 'ceph_version_when_created': 'ceph version 5f64facd06 (05f64facd06927d52075c67e8f3fb02753c5825c) squid (dev)', 'cpu': '11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz', 'created_at': '2024-12-01T08:08:29.941791Z', 'default_device_class': 'hdd', 'device_ids': '', 'device_paths': '', 'devices': '', 'distro': 'fedora', 'distro_description': 'Fedora Linux 40 (Workstation Edition)', 'distro_version': '40', 'front_addr': '[v2:127.0.0.1:6818/298274492,v1:127.0.0.1:6819/298274492]', 'front_iface': '', 'hb_back_addr': '[v2:127.0.0.1:6824/298274492,v1:127.0.0.1:6825/298274492]', 'hb_front_addr': '[v2:127.0.0.1:6822/298274492,v1:127.0.0.1:6823/298274492]', 'journal_rotational': '1', 'kernel_description': '#1 SMP PREEMPT_DYNAMIC Fri Nov  1 16:09:34 UTC 2024', 'kernel_version': '6.11.6-200.fc40.x86_64', 'mem_swap_kb': '8388604', 'mem_total_kb': '65538576', 'network_numa_unknown_ifaces': 'back_iface,front_iface', 'os': 'Linux', 'osd_data': '/home/rsachere/Src/redhat/ceph/build/dev/osd2', 'osd_objectstore': 'bluestore', 'osdspec_affinity': '', 'rotational': '1'}}}
```

When I try this from the repl putting the above in a file with `things = ....` then it works fine:
```
rsachere@fedora:~/Src/redhat/ceph/src/pybind/mgr/chad$ python -m rule_engine.debug_repl --edit-file osd_metadata.debug 
executing: osd_metadata.debug
rule > [ osd_metadata[osd].mem_swap_kb.to_int > 0 for osd in osd_metadata.keys ]
result: 
(True, True, True)
```

Then I want to built it into my code, I have some debug output:
```
Rule [ osd_metadata[osd].mem_swap_kb.to_int > 0 for osd in osd_metadata.keys ] found.
Rule [ osd_metadata[osd].mem_swap_kb.to_int > 0 for osd in osd_metadata.keys ] is valid: True.
```

I use the above dict, I even tried to check it's type and repr it to the log:
```
 <class 'dict'>.
```

So I'ts a dict allright, and contains the `config` key, but I get this rule engine error:
```
 syntax error <SymbolResolutionError message="unknown symbol: 'osd_metadata'" suggestion=None >
````

That's a traceback:
```
2024-12-01T22:33:01.933+0100 7f08f3a006c0 -1 Traceback (most recent call last):
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/module.py", line 281, in serve
    self.run_rules()
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/module.py", line 248, in run_rules
    matches = tuple(rule_parser.filter(data))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/engine.py", line 614, in filter
    yield from (thing for thing in things if self.matches(thing))
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/engine.py", line 614, in <genexpr>
    yield from (thing for thing in things if self.matches(thing))
                                             ^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/engine.py", line 657, in matches
    return bool(self.evaluate(thing))
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/engine.py", line 646, in evaluate
    return self.statement.evaluate(thing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 1155, in evaluate
    return self.expression.evaluate(thing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 395, in evaluate
    return self._evaluator(thing)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 600, in __op_arithmetic
    left_value = self.left.evaluate(thing)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 395, in evaluate
    return self._evaluator(thing)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 431, in _op_add
    left_value = self.left.evaluate(thing)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 395, in evaluate
    return self._evaluator(thing)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 431, in _op_add
    left_value = self.left.evaluate(thing)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 796, in evaluate
    resolved_obj = self.object.evaluate(thing)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 796, in evaluate
    resolved_obj = self.object.evaluate(thing)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/ast.py", line 1022, in evaluate
    value = self.context.resolve(thing, self.name, scope=self.scope)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/engine.py", line 540, in resolve
    return self.__resolver(thing, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsachere/Src/redhat/ceph/src/pybind/mgr/chad/rule_engine/engine.py", line 86, in resolve_item
    raise errors.SymbolResolutionError(name, thing=thing)
rule_engine.errors.SymbolResolutionError: config
```

I am not sure what's going on, Probably something pretty simple. The code seems rather simple to me:

```
     def run_rules(self):
 
         for rule in self.rules['rules']:
             try:
                 r = rule_engine.Rule(rule['rule'])
             except rule_engine.RuleSyntaxError as error:
                 raise object_format.ErrorResponse.wrap(error)
 
             self.log.debug('CHAD-RULE: Rule {} found.'.format(rule['rule']))
             self.log.debug('CHAD-RULE: Rule {} is valid: {}.'.format(rule['rule'], r.is_valid(rule['rule'])))
             self.log.debug('CHAD-RULE: {}.'.format(repr(self._get_object(rule['object']))))
             self.log.debug('CHAD-RULE: {}.'.format(type(self._get_object(rule['object']))))
             data = self._get_object(rule['object'])
 
             try:
                 matches = tuple(r.filter(data))
             except Exception as error:
                 self.log.debug('CHAD-RULE: syntax error {}'.format(repr(error)))
 
             self.log.debug('CHAD-RULE: -------------')
 
 #            if not matches:
 #                self.log.debug('CHAD-RULE: Rule {} does not match'.format(rule['description']))
 #                continue
 #
             self.log.debug('CHAD-RULE: Rule {} matches'.format(rule['description']))
```

I would appreciate any hints to what is actually the problem.

Thank you,

**Comment by rsacherer** [comment]
we can close this now.

**Comment by rsacherer** [comment]
Closing
